# Checkpoints

**CP1**:
Given the list $[A, B, C]$, use the `itertools` module to generate all possible
combinations of 2 elements.

**Expected Output**:
$$
 (A, B) \\
 (A, C) \\
 (B, C)
$$

In [4]:
import itertools
elements = ['A', 'B', 'C']

combinations = list(itertools.combinations(elements, 2))

for combination in combinations:
    print(combination)

('A', 'B')
('A', 'C')
('B', 'C')


**CP2**:
Use the `itertools` module to create a sequence that cycles through
['Python', 'is', 'fun'] infinitely. Print the first 10 elements of the sequence.

**Expected Output**:
$$
Python \\
is\\
fun\\
Python\\
is\\
fun\\
Python\\
is\\
fun\\
Python
$$

In [5]:
sequence = itertools.cycle(['Python', 'is', 'fun'])

for _ in range(10):
    print(next(sequence))

Python
is
fun
Python
is
fun
Python
is
fun
Python


**CP3**:
Use the `glob` module to list all python (.py) files in your current working directory.




In [6]:
import glob

python_files = glob.glob('*.py')

for file in python_files:
    print(file)

**CP4**: You are given the following HTML content below. Write a function that uses BeautifulSoup to parse the HTML and extract the text inside the   '$<p>$'   tag.


In [7]:
html_content= "<html><body><div class='main'><h1>Welcome to AI</h1><p>AI is transforming the world</p></div></body></html>"

In [10]:
from bs4 import BeautifulSoup

def extract_text_from_html(html_content):
    soup = BeautifulSoup(html_content, 'html.parser')
    paragraph_text = soup.find('p').get_text()

    return paragraph_text
extract_text_from_html(html_content)

'AI is transforming the world'

**CP5**: Write a function that uses the re module to replace all occurrences of the word "AI" with "Artificial Intelligence" in a given text.

In [12]:
import re

def replace_word(text):
    replaced_text = re.sub(r'\bAI\b', 'Artificial Intelligence', text)
    return replaced_text
text = "AI is a branch of computer science."
replaced_text = replace_word(text)
replaced_text


'Artificial Intelligence is a branch of computer science.'

**CP6**: Create a numpy array of 10 zeros.

In [14]:
import numpy as np

zeros_array = np.zeros(10)
zeros_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**CP7** Create a numpy array of the integers from 10 to 49.

In [16]:
array = np.arange(10, 50)
array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

**CP8**: Create a 3x3 numpy matrix, filled with values ranging from 0 to 8.

In [17]:
array = np.arange(9)
matrix = array.reshape(3, 3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**CP9**: Explain why machine learning models require large amounts of data? What does it mean for an amount of data to be **large**?

Machine learning models require large amounts of data to improve their accuracy and generalization. Large data sets provide more diverse examples, enabling the model to capture a wider range of patterns and variations in the data. This helps the model to make more reliable predictions and handle real-world complexities. "Large" data refers to having a sufficient number of diverse instances that adequately cover the variations and patterns in the problem domain. It helps reduce bias, improve feature representation, enhance stability, and mitigate overfitting.

**CP10**: Explain 2 ways AI can be used in an adverserial way, and what can be done to prevent it.

AI can be used in harmful ways through techniques like tricking security systems or creating fake videos. To prevent this, we need strong security measures, like training AI models to be more resistant to attacks and developing ways to detect and stop malicious AI use.